[project]
name = "python-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "opencv-python-headless>=4.11.0.86",
    "timm>=1.0.15",
    "torch>=2.6.0",
]
